config/routes.rb
JarinudomCom::Application.routes.draw do

  match 'resume' => 'resume#index', :as => :resume

  resources :adsense, :only => [:show]

  root :to => "home#index"

end

app/models/certification.rb
class Certification < ActiveRecord::Base
  
  validates_presence_of :name, :start_date
  
end

app/models/education.rb
class Education < ActiveRecord::Base
  
  validates_presence_of :name, :location, :date
  
end

app/models/job.rb
class Job < ActiveRecord::Base
  
  validates_presence_of :position, :employer, :location, :start_date, :description
  
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  
  validates_presence_of :name, :address, :city, :state, :zip,
                        :phone, :email
                              
  validates_format_of :email,
                      :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
                      
  validates_format_of :website,
                      :with => /^http\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?$/
  
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  
  validates_presence_of :name, :level
  validates_inclusion_of :level, :in => 1..3
  
end

app/controllers/adsense_controller.rb
class AdsenseController < ApplicationController

  def show
    render params[:id], :layout => false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  
  def index
    @resume = Resume.first
    @jobs = Job.order("(case WHEN end_date IS NULL THEN 1 ELSE 0 END) DESC, end_date DESC, start_date DESC")
    @skills = Skill.order("level ASC, name ASC")
    @educations = Education.order("date DESC")
    @certifications = Certification.order("(case WHEN end_date IS NULL THEN 1 ELSE 0 END) DESC, end_date DESC, start_date DESC")
  end

end

app/helpers/adsense_helper.rb
module AdsenseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
  def date_or_present(date)
    date ? date.to_s(:month_year) : 'Present'
  end
end

app/views/adsense/index.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title
    %style
      :plain
        html, body {  
          margin: 0px;  
          padding: 0px;  
          border: 0px;  
          width: 160px;
          height: 600px;
        }  
      
  %body
    :javascript
      document.domain = 'posterous.jarinudom.com';
      var clicky_custom = {};
      clicky_custom.href = '#{URI.parse(request.env["HTTP_REFERER"]).path}';
      

    :plain
      <script type="text/javascript"><!--
      google_ad_client = "ca-pub-3727069797306625";
      /* jarin.posterous.com */
      google_ad_slot = "9026956698";
      google_ad_width = 160;
      google_ad_height = 600;
      //-->
      </script>
      <script type="text/javascript"
      src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>

    :plain
      <script type="text/javascript">
      var clicky = { log: function(){ return; }, goal: function(){ return; }};
      var clicky_site_id = 209818;
      (function() {
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = ( document.location.protocol == 'https:' ? 'https://static.getclicky.com/js' : 'http://static.getclicky.com/js' );
        ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
      })();
      </script>
      <noscript><p><img alt="Clicky" width="1" height="1" src="http://in.getclicky.com/209818ns.gif" /></p></noscript>

app/views/adsense/jarin.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title
    %style
      :plain
        html, body {  
          margin: 0px;  
          padding: 0px;  
          border: 0px;  
          width: 160px;
          height: 600px;
        }  
      
  %body
    :plain
      <script type="text/javascript"><!--
      google_ad_client = "ca-pub-3727069797306625";
      /* jarin.posterous.com */
      google_ad_slot = "9026956698";
      google_ad_width = 160;
      google_ad_height = 600;
      //-->
      </script>
      <script type="text/javascript"
      src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>

app/views/adsense/jarinheit.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title
    %style
      :plain
        html, body {  
          margin: 0px;  
          padding: 0px;  
          border: 0px;  
          width: 160px;
          height: 600px;
          background-color: #232522;
        }  
      
  %body
    :plain
      <script type="text/javascript"><!--
      google_ad_client = "ca-pub-3727069797306625";
      /* jarinheit.posterous.com */
      google_ad_slot = "9140912766";
      google_ad_width = 160;
      google_ad_height = 600;
      //-->
      </script>
      <script type="text/javascript"
      src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>

app/views/home/index.html.haml
- content_for :head do
  = javascript_include_tag "https://www.tungle.me/portal/js/plugins/tungle.mwmWidget.js"
  :javascript
    $(function(){
      $('.noisy').noisy({
        intensity: 1, 
        opacity: 0.06,
        monochrome: false
      });
    });

%section#banner.row
  %article.col.col_10.align_left.hyphenate
    :textile
      Hi, my name's Jarin Udom. I'm the founder and lead developer of "Robot Mode LLC":http://robotmodehq.com, a web and mobile development company in San Diego.
      
      I work with all kinds of technology, but I specialize in web development with Ruby on Rails and writing iPhone and iPad apps. I also help companies interact with their customers and become more efficient through technology.
      
      
  %figure.col.col_6.align_center
    = image_tag "jarin.jpg", :alt => "Jarin Udom"
    %p.caption Imperial Palace Gardens, Tokyo, Japan
    
.clear
    
%section#content.row.noisy
  %aside#fun_facts
    %p.noisy This site was developed on a Mac with Rails 3, HTML5, CSS3, HAML, SASS, and 52framework. Cutting edge!
    
  %section.col.col_11
    %article.hyphenate
      :textile
        h2. Ok, tell me something awesome.
        
        h4. Here are some nice things people much smarter than me have said:
        
        bq. "Jarin is a well rounded and an analytical entrepreneur, he has a keen sense of innovation and consumers grasp of technology, a great fit for any organization." %(source)Chris Wallace, Co-Founder, "3Crowd":http://www.3crowd.com/company/management/%
        
        bq. "Jarin is a very talented developer, project manager and thinker. During the time I worked with him I was regularly impressed by his forward thinking ideas and methods. Not only does he have the skills as a developer, but the ability to effectively manage others to get the job done. I observed him lead projects from inception to completion while incorporating innovative strategies and solutions along the way, one in particular that was a first for our industry and an idea all his own. He is extremely knowledgeable and competent in his field and an asset to any company." %(source)Robert Swisher, CTO, "Business.com":http://business.com%
        
        bq. "Jarin is the next best thing to Google. Jarin has the ability to read very complex technical books that take most people months or years to articulate and apply them almost immediately. I witnessed Jarin read a CCNA book twice cover to cover and then pass his exam on the first attempt. My phone a friend call for a million dollars will be to Jarin." %(source)Josh Cowan, Senior Network Engineer, "Juno Technologies":http://www.juno-tech.com/%
        
    %article.hyphenate
      :textile
        h2. Cool. Gotten any press?
        
        h3. Smartphone Apps Fuel Business
      
      %ul.inline_links
        %li.first= link_to "Wall Street Journal", "http://online.wsj.com/article/SB125071635069144197.html"
        %li= link_to "Entrepreneur Magazine", "http://www.entrepreneur.com/technology/newsandtrends/article205368.html"
        %li= link_to "Smart Money Small Business", "http://www.smsmallbiz.com/technology/Smartphone_Apps_Fuel_Business.html"
              
      :textile
        Diana Ransom interviewed me for an article how independent iPhone developers can help small businesses attract new customers and increase revenue. Mad props to "Tobias L&uuml;tke":http://blog.leetsoft.com/ of "Shopify":http://www.shopify.com/?ref=robotmode for hooking up the interview.
        
        h3. Naughty America Is Building An iTunes For Porn
      
      %ul.inline_links
        %li.first= link_to "TechCrunch", "http://techcrunch.com/2008/10/08/come-and-get-it-naughty-america-is-building-an-itunes-for-porn/"
        %li= link_to "The Washington Post", "http://www.washingtonpost.com/wp-dyn/content/article/2008/10/08/AR2008100803175.html"
        
      :textile
        TechCrunch article about Naughty America Direct, an iTunes Store-like Adobe AIR application that I planned, managed, and helped develop. The secret to getting an article on TechCrunch? Write Mike Arrington an email at 3 in the morning, I guess. G4's Attack of the Show also did a segment on it, but it's no longer available on their website.
        
  %aside.col.col_5
      
    %section.first
      :textile
        h3. Around the Web
        
        * "Twitter":http://twitter.com/jarin
        * "Jarinheit":http://jarinheit.posterous.com
        My blog of programming stuff
        * "Jarin's Posterous":http://jarin.posterous.com
        Random links and videos
        * "Facebook":http://facebook.com/jarin
        * "LinkedIn":http://www.linkedin.com/in/jarinudom
        * "Pinboard":http://pinboard.in/u:jarin
        My bookmarks
        
    %section
      = link_to image_tag("http://www.w3.org/html/logo/badge/html5-badge-h-css3-semantics.png", :width => 165, :height => 64, :alt => "HTML5 Powered with CSS3 / Styling, and Semantics", :title => "HTML5 Powered with CSS3 / Styling, and Semantics"), "http://www.w3.org/html/logo/"

    %section
      %h3 Call or Meeting
      = javascript_include_tag "http://download.skype.com/share/skypebuttons/js/skypeCheck.js"
      = link_to image_tag("http://mystatus.skype.com/bigclassic/jarinudom", :style => "border: none;", :width => "182", :height => "44", :alt => "My status"), "skype:jarinudom?call"
      
      = image_tag "https://www.tungle.me/public/jarin/busyicon", :class => "tungle-me", :teml => "jarin"
      
      = javascript_include_tag "http://plancast.com/goodies/widgets/sidebar/1/936"
    
    %section
      :textile
        h3. Things I Use
        
        * "Basecamp":http://www.basecampHQ.com/?referrer=JARINUDOM
        Project management and collaboration
        * "Highrise":http://www.highriseHQ.com/?referrer=JARINUDOM
        CRM and business communications
        * "Backpack":http://www.backpackIT.com/?referrer=JARINUDOM
        Notes and snippets
        * "Shopify":http://www.shopify.com/?ref=robotmode
        e-commerce that even non-techies love
        * "Slicehost":https://manage.slicehost.com/customers/new?referrer=b408967bd7ff2edb81a5d12a51852f13
        Cheap, powerful hosting
        * "Github":http://github.com/jarinudom
        Version control
        * "Textmate":http://macromates.com
        Code editor extraordinaire
        
    %section
      :textile
        h3. Homies and Cronies
        
        * "Jason Hanes":http://sneaky.me
        Web developer
        * "Daryl Sterling":http://themightyafro.com
        Developer and ping pong champion
        * "Laura D":http://www.howilearnedtolive.com
        Bacon addict
        * "David Moye":http://www.aolnews.com/team/david-moye/
        Weird News Journalist and Public Relations
        
.clear

app/views/layouts/_footer.html.haml
%footer.row
  %section.col_16.col.align_center
    :textile
      &copy; 2010 Jarin Udom. You can use whatever you like from the "source code":http://github.com/jarinudom/jarinudom.com for whatever you want, except for images and content. Those are mine!

app/views/layouts/_header.html.haml
.row
  %header
    %h1.logo.left= link_to "Jarin Udom", root_path

    %nav.right
      %ul
        %li{:class => "#{current_page?(root_path) ? 'active' : ''}"}
          = link_to "Home", root_path
        / %li{:class => "#{current_page?(:controller => 'resume', :action => 'index') ? 'active' : ''}"}
        /   = link_to "Resume", resume_path
        %li
          = link_to "View Source", "http://github.com/jarinudom/jarinudom.com", :class => "skinny"
.clear

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %title= "Jarin Udom#{' - ' + @title if @title}"
    
    %meta{:name => "keywords", :content => "Jarin Udom, resume, Ruby on Rails, iPhone, iPad, developer, programmer, San Diego, CA, California"}
    %meta{:name => "description", :content => "Everything you ever wanted to know about Jarin Udom, a Ruby on Rails and iPhone/iPad developer in San Diego, CA"}
    
    / OpenID delegate
    %link{:rel => "openid.server", :href => "http://www.myopenid.com/server"}
    %link{:rel => "openid.delegate", :href => "http://jarinudom.myopenid.com/"}
    %link{:rel => "openid2.local_id", :href => "http://jarinudom.myopenid.com"}
    %link{:rel => "openid2.provider", :href => "http://www.myopenid.com/server"}
    %meta{'http-equiv' => "X-XRDS-Location",
          :content => "http://www.myopenid.com/xrds?username=jarinudom.myopenid.com"}

    = csrf_meta_tag

    = javascript_include_tag :defaults, "jquery.noisy.js", "html5.js", "Hyphenator.js"
    :javascript
      $(function(){
        $('body').noisy();
        Hyphenator.run();
      });
    
    / 52framework stylesheets
    = stylesheet_link_tag "reset", "general", "grid"
    / Custom stylesheets
    = stylesheet_link_tag "application", "#{controller_name}_#{action_name}"

    = yield :head
    
  %body

    = render :partial => "layouts/header"

    = yield

    = render :partial => "layouts/footer"
    
    / Clicky Analytics Code
    = javascript_include_tag "http://static.getclicky.com/js"
    :javascript
      clicky.init(209580);
    %noscript
      %p
        = image_tag "http://in.getclicky.com/209580ns.gif", :alt => "Clicky", :width => "1", :height => "1"
        
    / Google Analytics Code
    :javascript
      var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
      document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    :javascript
      try {
      var pageTracker = _gat._getTracker("UA-1396681-1");
      pageTracker._trackPageview();
      } catch(err) {}

    :javascript
      var $buoop = {
        newwindow: true
      }
      $buoop.ol = window.onload;
      window.onload=function(){
       if ($buoop.ol) $buoop.ol();
       var e = document.createElement("script");
       e.setAttribute("type", "text/javascript");
       e.setAttribute("src", "http://browser-update.org/update.js");
       document.body.appendChild(e);
      }

app/views/resume/index.html.haml
%section#resume.row
  #actions.col.col_16.align_right
    Print This
  #content.row
    #sidebar.col.col_4
      :textile
        h2. #{@resume.name}
        
        #{@resume.address}
        #{@resume.city}, #{@resume.state} #{@resume.zip}
        &#9742; #{@resume.phone}
        &#9993; #{mail_to @resume.email}
        &#9881; #{link_to @resume.website}
        
    #main.col.col_12
      - if @resume.summary
        #summary.col.col_12
          %h2 Summary
          %p= @resume.summary
          
      #skills.col.col_12
        %h2 Skills
        %ul
          - @skills.each do |skill|
            %li.skill{:class => "skill_#{skill.level}"}
              = image_tag "skill_#{skill.level}.png"
              = skill.name
            
      #jobs.col.col_12
        %h2 Experience
        - @jobs.each do |job|
          .job
            %h4
              %span.position= job.position
              at
              %span.employer= job.employer
            %p.meta
              %span.date& #{job.start_date.to_s(:month_year)} – #{date_or_present(job.end_date)},
              %span.location= "in #{job.location}"
            %p.description
              = job.description
              
      #education.col.col_12
        %h2 Education
        - @educations.each do |education|
          .education
            %h4
              %span.name= education.name
            %p.meta
              %span.date= education.date
              %span.location= "in #{education.location}"
            %p.description
              = education.description
      
      - if @certifications      
        #certifications.col.col_12
          %h2 Certifications
          - @certifications.each do |cert|
            .certification
              %h4
                %span.name= cert.name
                %span.date& #{cert.start_date.to_s(:month_year)} – #{date_or_present(cert.end_date)}

.clear